### PR TITLE
Fix bug of 'keyword' as subkeyword

### LINKED ISSUE #304: [PE-D][Tester C] Main keywords can be defined with the keyword "keyword"
There are no illegal user-defined keywords. Hence, it is possible to break the keyword system by
1. Entering the command `keyword --k patient --n keyword`.
2. Afterwards, keywords can no longer be added, edited or deleted. i.e command `keyword delete keyword` will invoke `patient delete keyword`. 
3. Hence, keyword commands will be unusable until data is deleted.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jedidiahC/ped#1

### PR DESCRIPTION
**Pull request by slackernoob**
Closes #304.

### CODE REVIEW

File: src/main/java/seedu/vms/model/keyword/Keyword.java [hunk 1]
```diff
@@ -10,6 +10,7 @@ public class Keyword {
     public static final String MAIN_BASIC_STRING = "basic";
     public static final String MAIN_EXIT_STRING = "exit";
     public static final String MAIN_HELP_STRING = "help";
+    public static final String MAIN_KEYWORD_STRING = "keyword";
```
Comment (francisyzy) [inline src/main/java/seedu/vms/model/keyword/Keyword.java:13]: Looks ok to me!

Was thinking why are your strings not from the feature parser. Hardcoding strings might be a pain to find in the future when changing keywords.

could take it from here:
```java
public class KeywordParser extends FeatureParser {
    public static final String FEATURE_NAME = "keyword";
```

File: src/main/java/seedu/vms/commons/core/Messages.java [hunk 2]
```diff
@@ -21,7 +21,7 @@ public class Messages {
             + "Please delete before creating a new keyword mapping with %s. \n";
     public static final String MESSAGE_INVALID_MAIN_KEYWORD = "Invalid main keyword! "
             + "Only %s, %s, and %s are allowed. \n";
-    public static final String MESSAGE_INVALID_SUB_KEYWORD = "Invalid new keyword! %s, %s, %s, %s, %s, "
+    public static final String MESSAGE_INVALID_SUB_KEYWORD = "Invalid new keyword! %s, %s, %s, %s, %s, %s,"
```
Comment (francisyzy) [inline src/main/java/seedu/vms/commons/core/Messages.java:24]: Hmm is there a better way of string formatting so that you don’t have to modify this every time you want to black list a word?

**Review by francisyzy — APPROVED** [review]
