### PR TITLE
Fix id not increasing

### LINKED ISSUE #353: ID numbering not consistent
When deleting ID2, then ID3, then adding new person, it takes on ID3. Should take ID4 instead.

Commands to type in order to trigger bug:

```
pat clear
patient add --n John Doe --p 98765432 --d 2001-03-19 --b B+ --a catfur, pollen --v covax
patient add --n John Doe --p 98765432 --d 2001-03-19 --b B+ --a catfur, pollen --v covax
patient add --n John Doe --p 98765432 --d 2001-03-19 --b B+ --a catfur, pollen --v covax
pat delete 2
pat delete 3
patient add --n John Doe --p 98765432 --d 2001-03-19 --b B+ --a catfur, pollen --v covax
```

https://user-images.githubusercontent.com/24467184/230121616-cd4378a4-84c9-4ee5-adc9-8773e680e9d5.mp4

### PR DESCRIPTION
**Pull request by daitenshionyan**
Fixes #353 

Also fixes issue where delete command will reset ID count when ID related managers are emptied. The fixed behaviour is the behavour before feature freeze. Bug was introduced from clear command fix.

### CODE REVIEW

**Review by nusE0726844 — APPROVED** [review]
LGTM

File: src/main/java/seedu/vms/model/ModelManager.java [hunk 1]
```diff
@@ -171,6 +171,11 @@ public void deletePatient(int id, boolean isForce) throws UnexpectedChangeExcept
         handlePatientChange(change);
     }
 
+    @Override
+    public void resetPatientIds() {
```
Comment (francisyzy) [inline src/main/java/seedu/vms/model/ModelManager.java:175]: Hey, would like to check if this method is being used anywhere. Should patient clear reset the ID count?
